# Generated by Django 2.0.7 on 2018-07-19 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='votes',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='city_or_town',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='email',
            field=models.EmailField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'FeMale')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:                                  L̥'+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Orissa'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TR', 'Tripura'), ('UK', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West bengal'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DH', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('LD', 'Lakshadweep'), ('PY', 'Pondicherry')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
